print('What do you get when you cross a snowman with a vampire?')
input()
print('frostbite!')
print()
print('What do dentists call an astronaughts cavity')
input()
print('a black hole!')
print()
print('knock knock.')
